# Generated by Django 4.2.2 on 2023-06-26 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_rename_sp_ak_creature_sp_atk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creature',
            new_name='PokedexCreature',
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_id', models.PositiveIntegerField(null=True)),
                ('nickname', models.CharField(max_length=64)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('pokedex_creature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokedexcreature')),
            ],
        ),
    ]
